#!/bin/bash
set -e

# Generate keys if not provided
[ -f keys/dhparam.pem ] ||
  openssl dhparam -out keys/dhparam.pem 2048

if [ ! -f keys/default.pem ]
then
  openssl genrsa -out keys/server-key.pem 2048
  openssl req -new -key keys/server-key.pem -out keys/server-csr.pem -subj /CN=*/
  openssl x509 -req -in keys/server-csr.pem -out keys/server-cert.pem -signkey keys/server-key.pem -days 3650
  cat keys/server-cert.pem keys/server-key.pem > keys/default.pem
fi

# Check is haproxy.cfg is valid before we start ucarp
haproxy -c -f /haproxy/haproxy.cfg

/usr/sbin/haproxy -f /haproxy/haproxy.cfg
sleep infinity # block forever
