#!/bin/bash
set -e
PIDFILE="/tmp/haproxy.pid"

reload() {
  echo "Reloading config"
  if ! haproxy -c -f /haproxy/haproxy.cfg
  then
    echo "invalid config, not reloading"
    return 1
  fi

  haproxy -p $PIDFILE -f /haproxy/haproxy.cfg -sf $(cat $PIDFILE)
}

# Generate keys if not provided
[ -f keys/dhparam.pem ] ||
  openssl dhparam -out keys/dhparam.pem 2048

if [ ! -f keys/default.pem ]
then
  openssl genrsa -out keys/server-key.pem 2048
  openssl req -new -key keys/server-key.pem -out keys/server-csr.pem -subj /CN=*/
  openssl x509 -req -in keys/server-csr.pem -out keys/server-cert.pem -signkey keys/server-key.pem -days 3650
  cat keys/server-cert.pem keys/server-key.pem > keys/default.pem
fi

# Check is haproxy.cfg is valid before we start ucarp
haproxy -c -f /haproxy/haproxy.cfg

/usr/sbin/haproxy -p $PIDFILE -f /haproxy/haproxy.cfg

trap reload SIGHUP
while true
do
  sleep infinity & # blocks forever but still make sure bash
  wait || :        # executes reload trap. See:
done               # http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html#sect_12_02_02
